cd ../../src
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=paradetox.yaml args='ue.calibrate\=False data.subsample_perc\=0.18 +ue.use_spectralnorm\=True training.num_train_epochs\=10 training.learning_rate\=2e-05 training.per_device_train_batch_size\=8 +training.weight_decay\=0.1' output_dir='../workdir/run_train_ensemble_series_90/paradetox/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=toxigen.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True training.num_train_epochs\=3 training.learning_rate\=5e-05 training.per_device_train_batch_size\=32 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/toxigen/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=implicithate.yaml args='ue.calibrate\=False data.subsample_perc\=0.09 +ue.use_spectralnorm\=True training.num_train_epochs\=15 training.learning_rate\=7e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0.01' output_dir='../workdir/run_train_ensemble_series_90/implicithate/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=jigsaw_toxic.yaml args='ue.calibrate\=False data.subsample_perc\=0.09 +ue.use_spectralnorm\=True training.num_train_epochs\=13 training.learning_rate\=3e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/jigsaw_toxic/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=twitter_hso.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True training.num_train_epochs\=4 training.learning_rate\=9e-06 training.per_device_train_batch_size\=16 +training.weight_decay\=0.01' output_dir='../workdir/run_train_ensemble_series_90/twitter_hso/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=sst5.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True training.num_train_epochs\=4 training.learning_rate\=9e-06 training.per_device_train_batch_size\=16 +training.weight_decay\=0.01' output_dir='../workdir/run_train_ensemble_series_90/sst5/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=20newsgroups.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True training.num_train_epochs\=12 training.learning_rate\=3e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/20newsgroups/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=amazon.yaml args='ue.calibrate\=False data.subsample_perc\=0.09 +ue.use_spectralnorm\=True training.num_train_epochs\=2 training.learning_rate\=5e-05 training.per_device_train_batch_size\=32 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/amazon/electra_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=paradetox.yaml args='ue.calibrate\=False data.subsample_perc\=0.18 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=7 training.learning_rate\=3e-05 training.per_device_train_batch_size\=16 +training.weight_decay\=0.1' output_dir='../workdir/run_train_ensemble_series_90/paradetox/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=toxigen.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=2 training.learning_rate\=5e-05 training.per_device_train_batch_size\=32 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/toxigen/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=implicithate.yaml args='ue.calibrate\=False data.subsample_perc\=0.09 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=9 training.learning_rate\=7e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0.01' output_dir='../workdir/run_train_ensemble_series_90/implicithate/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=jigsaw_toxic.yaml args='ue.calibrate\=False data.subsample_perc\=0.09 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=3 training.learning_rate\=5e-05 training.per_device_train_batch_size\=32 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/jigsaw_toxic/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=twitter_hso.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=6 training.learning_rate\=7e-06 training.per_device_train_batch_size\=32 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/twitter_hso/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=sst5.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=15 training.learning_rate\=7e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0' output_dir='../workdir/run_train_ensemble_series_90/sst5/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=20newsgroups.yaml args='ue.calibrate\=False data.subsample_perc\=0.9 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=9 training.learning_rate\=7e-05 training.per_device_train_batch_size\=64 +training.weight_decay\=0.01' output_dir='../workdir/run_train_ensemble_series_90/20newsgroups/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py
HYDRA_CONFIG_PATH=../configs/run_train_ensemble_series.yaml python ./run_train_ensemble_series.py task_configs=amazon.yaml args='ue.calibrate\=False data.subsample_perc\=0.09 +ue.use_spectralnorm\=True model.model_name_or_path\=bert-base-uncased training.num_train_epochs\=3 training.learning_rate\=9e-06 training.per_device_train_batch_size\=16 +training.weight_decay\=0.01' output_dir='../workdir/run_train_ensemble_series_90/amazon/bert_raw_sn/' cuda_devices=[0,1,2] script=run_glue.py