hydra:
  run:
    dir: ${output_dir}/${data.task_name}/${ue.dropout_type}_${ue.dropout_subs}/${data.subsample_perc}/${suffix}/${now:%Y-%m-%d}/${now:%H-%M-%S}-${repeat}
    
model:
    model_name_or_path: 'google/electra-base-discriminator'

ue:
    ue_type: 'mc' # mc,mc-dc,mc-dpp,sngp,ensemble
    dropout_type: 'MC'
    inference_prob: 0.1
    committee_size: 20
    dropout_subs: 'last'
    use_cache: True
    eval_passes: False
    calibrate: False
    dropout:
        max_n: 100
        max_frac: 0.4
        mask_name: 'ht_dpp'
        dry_run_dataset: 'eval'
        is_reused_mask: False
        use_ood_sampling: False
        mask_name_for_mask: 'rbf'
        committee_size: 20

training: ???
    
data:
    task_name: 'mrpc'
    subsample_perc: 0.
    max_seq_length: 128
    
cache_dir: '../workdir/cache/'
output_dir: '../workdir/results/'
seed: 42
suffix: ''
do_train: True
do_eval: True
do_ue_estimate: True
reset_params: False
repeat: ''

defaults:
  - training: electra_base